In [7]:
from multiprocessing import heap

#数据的导入
import pandas as pd
from pandas.core.algorithms import value_counts_arraylike

df = pd.read_csv('data/employees.csv')
print(type(df))
print(df.tail())
print(df.salary.mean())
#数据导出
df = df.tail(5)
df.to_csv('data/new.csv', index=False)

<class 'pandas.DataFrame'>
     employee_id first_name last_name     email  phone_number      job_id  \
102          202        Pat       Fay      PFAY  603.123.6666      MK_REP
103          203      Susan    Mavris   SMAVRIS  515.123.7777      HR_REP
104          204    Hermann      Baer     HBAER  515.123.8888      PR_REP
105          205    Shelley   Higgins  SHIGGINS  515.123.8080      AC_MGR
106          206    William     Gietz    WGIETZ  515.123.8181  AC_ACCOUNT

      salary  commission_pct  manager_id  department_id
102   6000.0             NaN       201.0           20.0
103   6500.0             NaN       101.0           40.0
104  10000.0             NaN       101.0           70.0
105  12000.0             NaN       101.0          110.0
106   8300.0             NaN       205.0          110.0
6461.682242990654

In [23]:
#json数据
# df = pd.read_json('data/test.json')
import pandas as pd
import json

# 读取JSON文件
with open('data/test.json') as f:
    data = json.load(f)

# 打印data的类型
print(type(data))

# 转成DataFrame
df = pd.DataFrame(data['users'])

# 打印df的类型
print(type(df))

# 显示表格（视频里就是这一行）
df

<class 'dict'>
<class 'pandas.DataFrame'>

   id name  age                 email  is_active   join_date
0   1  寮犱笁   28  zhangsan@example.com       True  2022-03-15
1   2  鏉庡洓   35      lisi@example.com      False  2021-11-02
2   3  鐜嬩簲   24    wangwu@example.com       True  2023-01-20

In [45]:
#缺失值处理
import pandas as pd
import numpy as np
s = pd.Series([1,2,np.nan,None,pd.NA])
df = pd.DataFrame([[1,pd.NA,2],[2,3,5],[None,4,6]])
# print(s)
#查看是否是缺失值
print(s.isna())
print(s.isnull())
print(df.isna())
print(df.isnull())
print(df.isna().sum())
print(df.isnull().sum())
print(s.isna().sum())#查看缺失值的个数
print('-'*30)
#剔除缺失值
print(s.dropna())
print(df.dropna())#有缺失值删除一整条记录
print('-'*30)
print(df.dropna(how='all'))#如果所有的值都是缺失值才删除
print('-'*30)
print(df.dropna(thresh=2))#至少有n个值不是缺失值，就保留
print('-'*30)
print(df.dropna(axis=1))#剔除一整列的记录
# print(df.dropna(subset=['第一列']))#如果某列又缺失值则删除这一行

0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool
       0      1      2
0  False   True  False
1  False  False  False
2   True  False  False
       0      1      2
0  False   True  False
1  False  False  False
2   True  False  False
0    1
1    1
2    0
dtype: int64
0    1
1    1
2    0
dtype: int64
3
------------------------------
0    1
1    2
dtype: object
     0  1  2
1  2.0  3  5
------------------------------
     0     1  2
0  1.0  <NA>  2
1  2.0     3  5
2  NaN     4  6
------------------------------
     0     1  2
0  1.0  <NA>  2
1  2.0     3  5
2  NaN     4  6
------------------------------
   2
0  2
1  5
2  6

In [57]:
#缺失值填充
df = pd.read_csv('data/weather_withna.csv')
df.tail()
df.isna().sum(axis=0)
df.head()
print(df.fillna({'temp_max':20}).tail())#使用字典来填充
print(df.fillna(df[['temp_min','wind']].mean()).tail())#使用统计值填充
print(df.ffill().tail())#front用前面相邻值
print(df.bfill().tail())#behind用附近的值填充

            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   NaN     NaN
1457  2015-12-28            NaN      20.0       NaN   NaN     NaN
1458  2015-12-29            NaN      20.0       NaN   NaN     NaN
1459  2015-12-30            NaN      20.0       NaN   NaN     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min      wind weather
1456  2015-12-27            NaN       NaN  7.877202  3.242055     NaN
1457  2015-12-28            NaN       NaN  7.877202  3.242055     NaN
1458  2015-12-29            NaN       NaN  7.877202  3.242055     NaN
1459  2015-12-30            NaN       NaN  7.877202  3.242055     NaN
1460  2015-12-31           20.6      12.2  5.000000  3.800000    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [60]:
import pandas as pd
data = {
    "name": ['alice', 'alice', 'bob', 'alice', 'jack', 'bob'],
    "age": [26, 25, 30, 25, 35, 30],
    'city': ['NY', 'NY', 'LA', 'NY', 'SF', 'LA']
}
df = pd.DataFrame(data)
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [66]:
df.duplicated()#检查重复，一整条记录都为相同标记为重复，返回true
df.drop_duplicates()#去除重复
df.drop_duplicates(subset=['city'])#根据指定的列去重
df.drop_duplicates(subset=['city'], keep='last')#保留最后一次出现的

    name  age city
3  alice   25   NY
4   jack   35   SF
5    bob   30   LA

In [69]:
#数据类型的转换
df = pd.read_csv('data/sleep.csv')
df.dtypes

person_id                    int64
gender                         str
age                          int64
occupation                     str
sleep_duration             float64
sleep_quality              float64
physical_activity_level      int64
stress_level                 int64
bmi_category                   str
blood_pressure                 str
heart_rate                   int64
daily_steps                  int64
sleep_disorder                 str
dtype: object

In [75]:
df['age'] = df['age'].astype('int16')
df['gender'] = df['gender'].astype('category')
df.gender

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, str): ['Female', 'Male']

In [79]:
df['is_male'] = df['gender'].map({'Female':True, 'Male':False})
df.is_male

0      False
1       True
2      False
3      False
4      False
       ...
395     True
396     True
397     True
398     True
399    False
Name: is_male, Length: 400, dtype: category
Categories (2, bool): [True, False]

In [88]:
#数据变形
import pandas as pd
data = {
'ID': [1, 2],
'name':['alice','bob'],
'Math':[90,85],
'English': [88, 92],
'Science': [95, 89]
}
# 2. 创建DataFrame
df = pd.DataFrame(data)

# 3. 宽表转长表（正确用法）
df_long = pd.melt(
    df,
    id_vars=['ID', 'name'],   # 保留的列（注意这里列名是'name'，和上面data里的键一致）
    var_name='科目',           # 原来的列名（Math/English/Science）会变成这一列的值
    value_name='成绩'          # 原来的列值会变成这一列的值
)
df_long.sort_values('name')
# 查看结果

   ID   name       科目  成绩
0   1  alice     Math  90
2   1  alice  English  88
4   1  alice  Science  95
1   2    bob     Math  85
3   2    bob  English  92
5   2    bob  Science  89

In [109]:
#分组聚合
#df.group(‘分组的字段’)['聚合的字段']
df = pd.read_csv('data/employees.csv')
print(df['department_id'].isna().sum())#查找是否有缺失值
df= df.dropna(subset=['department_id'])#删除这一列有缺失值的
print(df['department_id'].isna().sum())
df['department_id'] = df['department_id'].astype('int64')
#计算不同部门的平均薪资
df.groupby('department_id').groups#查看分组情况
df.groupby('department_id').get_group(10)#查看具体的某个分组数据
df.groupby('department_id')[['salary']].mean()

1
0

                     salary
department_id
10              4400.000000
20              9500.000000
30              4150.000000
40              6500.000000
50              3475.555556
60              5760.000000
70             10000.000000
80              8955.882353
90             19333.333333
100             8600.000000
110            10150.000000

In [114]:
#企鹅数据分析
#1.导入必要的库
import pandas as pd
import numpy as np
#2.导入数据 喙
df = pd.read_csv('data/penguins.csv')
df.head(5)
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   species            344 non-null    str
 1   island             344 non-null    str
 2   bill_length_mm     342 non-null    float64
 3   bill_depth_mm      342 non-null    float64
 4   flipper_length_mm  342 non-null    float64
 5   body_mass_g        342 non-null    float64
 6   sex                333 non-null    str
dtypes: float64(4), str(3)
memory usage: 18.9 KB

In [118]:
#3.数据清洗
#缺失值检查
print(df.isna().sum())
df.dropna(inplace=True)

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [120]:
df.isna().sum()

species              0
island               0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_g          0
sex                  0
dtype: int64

In [125]:
#4.数据特征的构造
df['sex'] = df['sex'].astype('category')#数据类型转换
df['bill_ratio'] = df['bill_length_mm']/df['bill_depth_mm']

In [133]:
#5.数据分析
#数据分箱，把体重分为低中高三个等级
labels = ['低','中','高']
df['mass_level'] = pd.cut(df['body_mass_g'],bins=3,labels=labels)
print(df['mass_level'].value_counts())
#按岛屿、性别分组分析
df.groupby(['sex']).agg({
    'body_mass_g':['mean','std'],
})
df.groupby(['island']).agg({
    'body_mass_g':['mean','std'],
})

mass_level
低    150
中    128
高     55
Name: count, dtype: int64

           body_mass_g
                  mean         std
island
Biscoe     4719.171779  790.860069
Dream      3718.902439  412.935581
Torgersen  3708.510638  451.846351

In [136]:
#1.导入库
import pandas as pd
#2.导入数据
df = pd.read_csv('data/sleep.csv')
df.head()
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                400 non-null    int64
 1   gender                   400 non-null    str
 2   age                      400 non-null    int64
 3   occupation               400 non-null    str
 4   sleep_duration           400 non-null    float64
 5   sleep_quality            400 non-null    float64
 6   physical_activity_level  400 non-null    int64
 7   stress_level             400 non-null    int64
 8   bmi_category             400 non-null    str
 9   blood_pressure           400 non-null    str
 10  heart_rate               400 non-null    int64
 11  daily_steps              400 non-null    int64
 12  sleep_disorder           110 non-null    str
dtypes: float64(2), int64(6), str(5)
memory usage: 40.8 KB

,person_id,age,sleep_duration,sleep_quality,physical_activity_level,stress_level,heart_rate,daily_steps
count,400.000000,400.000000,400.000000,400.000000,400.000000,400.00000,400.000000,400.000000
mean,200.500000,39.950000,8.041250,6.125750,64.985000,5.47250,75.990000,11076.510000
std,115.614301,14.038883,2.390787,1.975733,32.297874,2.80873,15.099334,5364.789364
min,1.000000,18.000000,4.100000,1.000000,10.000000,1.00000,50.000000,2067.000000
25%,100.750000,29.000000,5.900000,4.700000,35.000000,3.00000,63.000000,6165.250000
50%,200.500000,40.000000,8.200000,6.100000,65.500000,5.00000,77.000000,11785.500000
75%,300.250000,49.000000,10.125000,7.425000,94.000000,8.00000,90.000000,15878.000000
max,400.000000,90.000000,12.000000,10.000000,120.000000,10.00000,100.000000,19958.000000

In [150]:
#3.数据清洗
df.isna().sum()
# 方法1：先判断列是否存在，再删除
if 'sleep_disorder' in df.columns:
    df.drop(columns='sleep_disorder', inplace=True)

# 方法2：用 errors='ignore' 参数，不存在也不报错
df.drop(columns='sleep_disorder', inplace=True, errors='ignore')
df.isna().sum()

person_id                  0
gender                     0
age                        0
occupation                 0
sleep_duration             0
sleep_quality              0
physical_activity_level    0
stress_level               0
bmi_category               0
blood_pressure             0
heart_rate                 0
daily_steps                0
dtype: int64

In [166]:
#4.数据转换，数据特征构造
#先处理字符串，因为字符串类型的文本，模型看不懂，没法直接计算，必须转成数字 / 分类类型才能分析、建模。
df['gender'] = df['gender'].astype('category')
# df.info()#字符串已经变成分类了
df.head()
df['occupation'].value_counts()#先看能不能分类： 什么时候适合转 category？
# 满足这两个条件：
# 取值是固定选项：比如性别、职业、学历、等级、城市等，只有有限的几种值。
# 重复率高：比如 1000 行数据里，只有 5 个不同的值，重复越多，省内存的效果越明显。
df['occupation'] = df['occupation'].astype('category')
df[['high','low']]=df['blood_pressure'].str.split('/',expand=True)


#睡眠质量分箱
labels = ['差','中','优']
df['quality_level'] = pd.cut(df['sleep_quality'],bins=3,labels=labels)
age_labels=['青少年','中年','老年']
df['age_level'] = pd.cut(df['age'],bins=3,labels=age_labels)
df.head()

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,high,low,quality_level,age_level
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,124,70,中,青少年
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,131,86,中,中年
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,122,70,中,中年
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,124,72,优,青少年
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,133,78,优,老年

In [168]:
#5.数据分析与统计
print(df['bmi_category'].value_counts())

bmi_category
Overweight     109
Underweight    102
Obese           98
Normal          91
Name: count, dtype: int64

In [170]:
#根据不同BIMI分组，睡眠质量
df.groupby('bmi_category').agg({
    'sleep_duration':['mean','std'],
    'sleep_quality':['mean','std'],
})

             sleep_duration           sleep_quality
                       mean       std          mean       std
bmi_category
Normal             7.794505  2.418878      6.342857  1.773580
Obese              8.072449  2.412074      6.189796  1.924047
Overweight         8.274312  2.275286      6.101835  2.160589
Underweight        7.982353  2.474960      5.896078  1.992606